server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2020

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.zcbigdata.mybits_demo.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
